### ISSUE TITLE
of_net.c: In function 'read_mtd_mac_address':  //编译出错

### ISSUE THREAD

**Issue by bzzjh** [Lienol/lean-lede#43]
https://github.com/Lienol/lean-lede/commit/7c7a6f2e5548ef6bbad040832829c3e522e741bf
git pull,编译出错。
问题在于：
681-NET-add-of_get_mac_address_mtd.patch 
681-NET-add-of_get_mac_address_mtd.patch 
681-NET-add-of_get_mac_address_mtd.patch 
这三个patch导致，需要回退即可解决
多谢!

**Comment by Lienol** [comment]
同步上游了
